# Generated by Django 5.1.6 on 2025-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_background_image_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('bread', 'Хліб'), ('cake', 'Торт'), ('cookie', 'Печиво'), ('drink', 'Напій'), ('semi-finished product', 'Напівфабрикат')], default='bread', max_length=30, verbose_name='Тип продукту'),
        ),
    ]
