# Generated by Django 5.1.6 on 2025-05-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_subscriber_options_alter_subscriber_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Cклад'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=100, verbose_name='Вага'),
        ),
    ]
